// src/pages/contact.jsx
import React, { memo } from "react"

import Layout from "../components/layout/layout"

export default memo(({ location }) => (
  <Layout location={location} title="Contact">
    <form
      className="d-flex flex-column align-items-center"
      name="Contact"
      method="POST"
      data-netlify={true}
      netlify-honeypot="bot-field"
    >
      <input type="hidden" name="bot-field" />
      <input type="hidden" name="form-name" value="Contact" />

      <div className="form-group w-75">
        <label htmlFor="name">Name (Optional)</label>
        <input className="form-control" type="text" name="name" id="name" />
      </div>

      <div className="form-group w-75">
        <label htmlFor="message">Message</label>
        <textarea
          className="form-control"
          name="message"
          id="message"
          rows={7}
          required={true}
        />
      </div>

      <button className="btn btn-primary w-75" type="submit">
        Send
      </button>
    </form>
  </Layout>
))

// pages/contact.vue
<template>
  <v-container>
    <v-row>
      <v-col>
        <h1 class="text-center">Contact</h1>
      </v-col>
    </v-row>

    <v-divider class="my-5"></v-divider>

    <v-row justify="center">
      <v-col lg="8" sm="10">
        <v-form
          :netlify="true"
          :novalidate="false"
          data-netlify="true"
          method="POST"
          name="Contact"
          netlify-honeypot="bot-field"
        >
          <input type="hidden" name="form-name" value="Contact" />

          <div v-show="false">
            <label>
              Don’t fill this out if you're human:
              <input name="bot-field" />
            </label>
          </div>

          <v-text-field
            autofocus
            autocomplete="name"
            clearable
            label="Name (Optional)"
          ></v-text-field>

          <v-textarea label="Message" required></v-textarea>

          <v-btn block type="submit">Submit</v-btn>
        </v-form>
      </v-col>
    </v-row>
  </v-container>
</template>

<script>
export default {
  head() {
    return {
      title: 'Contact'
    }
  }
}
</script>
